// <auto-generated />
using System;
using DjMixOrganizer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DjMixOrganizer.Data.Migrations
{
    [DbContext(typeof(DjMixDbContext))]
    [Migration("20260726182453_CanonicalizeDbMusicalKey")]
    partial class CanonicalizeDbMusicalKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DjMixOrganizer.Core.Models.Mix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mixes");
                });

            modelBuilder.Entity("DjMixOrganizer.Core.Models.MixTrackEntry", b =>
                {
                    b.Property<Guid>("MixId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.HasKey("MixId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("MixTrackEntries", (string)null);
                });

            modelBuilder.Entity("DjMixOrganizer.Core.Models.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Artist")
                        .HasColumnType("longtext");

                    b.Property<double?>("Bpm")
                        .HasColumnType("double");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MusicalKey")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("DjMixOrganizer.Core.Models.MixTrackEntry", b =>
                {
                    b.HasOne("DjMixOrganizer.Core.Models.Mix", null)
                        .WithMany("Tracks")
                        .HasForeignKey("MixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DjMixOrganizer.Core.Models.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("DjMixOrganizer.Core.Models.Mix", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
